repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.0.1
    hooks:
      - id: check-added-large-files # Prevent giant files from being committed
      - id: check-ast # Check whether the files parse as valid python
      - id: check-json # Check json files for parseable syntax
      - id: check-merge-conflict # Check for files that contain merge conflict strings
      - id: check-toml # Checks toml files for parseable syntax
      - id: debug-statements # Check for debugger imports and `breakpoint()` calls in python
      - id: detect-private-key # Detect the presence of private keys
      - id: name-tests-test # Verify that test files are named correctly
      - id: pretty-format-json # Set a standard for formatting JSON files
        args: ["--autofix", "--no-sort-keys"]
      - id: requirements-txt-fixer # Sort entries in requirements.txt

  - repo: https://github.com/PyCQA/isort
    rev: 5.8.0
    hooks:
      - id: isort

  - repo: https://github.com/psf/black
    rev: 21.5b2
    hooks:
      - id: black

  - repo: https://github.com/asottile/blacken-docs
    rev: v1.10.0
    hooks:
      - id: blacken-docs
        additional_dependencies: [black==20.8b1]

  - repo: https://gitlab.com/PyCQA/flake8
    rev: 3.9.2
    hooks:
      - id: flake8
        exclude: src/sympc/sympc/

  - repo: https://github.com/PyCQA/bandit
    rev: 1.7.0
    hooks:
      - id: bandit
        args: ["--exclude", "tests"]



  - repo: https://github.com/pycqa/pydocstyle
    rev: 6.1.1  # pick a git hash / tag to point to
    hooks:
      - id: pydocstyle
        args:
          - --convention=google
        exclude: ^(tests/|src/sympc/sympc/)

  - repo: https://github.com/terrencepreilly/darglint
    rev: v1.8.0
    hooks:
      - id: darglint
        args:
          - -v 2
        exclude: ^tests/

  - repo: https://github.com/myint/autoflake
    rev: v1.4
    hooks:
      - id: autoflake
        args:
          - --in-place
          - --recursive
          - --remove-all-unused-imports
          - --ignore-init-module-imports
          - --remove-unused-variables
