[package]
name = "sympc-utils"
version = "0.1.0"
authors = ["George Muraru <murarugeorgec@gmail.com>"]
edition = "2018"

[lib]
name = "sympc_utils"
crate-type = ["cdylib"]


[dependencies.pyo3]
version = "0.13.2"
features = ["extension-module"]
